daily build changes so I can use d-i-unpack-helper
Add an optional second parameter to d-i-unpack-helper which is the number
of images to keep. If set, this will enable trimming. This requires a
full(-ish) copy of installer/build on the remote host.

Switch d-i-unpack-helper to using the same date format now used by
daily-build, to support builds more frequent than daily.

Improved comments about unclear variables, removed incorrect comment.

r53539

diff --git a/build/d-i-unpack-helper b/build/d-i-unpack-helper
--- a/build/d-i-unpack-helper
+++ b/build/d-i-unpack-helper
@@ -1,14 +1,19 @@
 #!/bin/sh
 
-# For use in .ssh/authorized keys as, e.g., command="~/d-i-unpack-helper alpha"
+# For use in .ssh/authorized keys as, e.g.,
+# command="~/d-i-unpack-helper alpha [30]"
 ARCH="$1"
+NUM_KEEP="$2"
+# Note that if NUM_KEEP is set, d-i-unpack-helper will expect
+# to find daily-build and the rest of the d-i installer/build/ tree in 
+# the same directory as itself.
 
 if [ -z "$BASEDIR" ]; then
 	BASEDIR=public_html/d-i/${ARCH:-images}
 fi
 
 if [ -z "$DIR" ]; then
-	DIR=`date +%Y-%m-%d`
+	DIR=$(date -u '+%Y%m%d-%H:%M')
 fi
 
 [ -n "$SSH_ORIGINAL_COMMAND" ] || exit 1
@@ -46,3 +51,19 @@ rm -rf $BASEDIR/$DIR
 mv $BASEDIR/${DIR}_RSYNC_IN_PROGRESS $BASEDIR/$DIR
 rm -rf $BASEDIR/daily
 ln -sf $DIR $BASEDIR/daily
+
+if [ -n "$NUM_KEEP" ]; then
+	cd $BASEDIR
+	BASEDIR=$(pwd)
+
+	MYDIR=$(dirname $0)
+	if [ ! -x "$MYDIR/daily-build" ]; then
+		echo "$MYDIR/daily-build not found, cannot trim" >&2
+		exit 1
+	fi
+	cd "$MYDIR"
+
+	export NUM_KEEP
+	export BASEDIR
+	TRIM_LOG=$BASEDIR/$DIR/trim.log HOST=local ./daily-build trim
+fi
