Implement clean method to include udebs from proposed-updates
For builds targeted at testing or stable, set USE_PROPOSED_UPDATES in
debian/rules to include udebs from the corresponding proposed-updates
suite. For details see build/README.

This replaces the hack to include a sources.list.udeb.local in uploads
for stable. Advantage of the new method is that the setting in the rules
file can be safely committed to SVN without affecting manual builds from
an SVN checkout.

It also means the buildds will now use locally defined mirrors instead of
the mirror "hardcoded" in sources.list.udeb.local.

r61207

diff --git a/build/Makefile b/build/Makefile
--- a/build/Makefile
+++ b/build/Makefile
@@ -575,9 +575,12 @@ sources.list.udeb:
 	if [ "$(MIRROR)x" != "x" ]; then \
 		echo "deb $(MIRROR) $(USE_UDEBS_FROM) $(UDEB_COMPONENTS)"; \
 	else \
-		gen-sources.list.udeb "$(SYSTEM_SOURCES_LIST)" $(USE_UDEBS_FROM) $(UDEB_COMPONENTS) ; \
+		gen-sources.list.udeb "$(SYSTEM_SOURCES_LIST)" $(USE_UDEBS_FROM) $(UDEB_COMPONENTS) $(USE_PROPOSED_UPDATES); \
 	fi) > $@
-
+	if [ "$(USE_PROPOSED_UPDATES)" = 1 ] && ! grep -q proposed-updates $@; then \
+		echo "ERROR: no valid source for $(USE_UDEBS_FROM)-proposed-updates"; \
+		exit 1; \
+	fi
 
 # Font generation.
 #
