Add error handling; minor other updates
r25848

diff --git a/doc/manual/scripts/create_xml b/doc/manual/scripts/create_xml
--- a/doc/manual/scripts/create_xml
+++ b/doc/manual/scripts/create_xml
@@ -13,28 +13,39 @@ language=${1:-pl}
 WORKDIR="./integrated"
 SOURCEDIR="$WORKDIR/en"
 PODIR="./po"
-LANGDIR="./$language.new"
+if [ -d "./$language/.svn" ] ; then
+    LANGDIR="./$language.new"
+else
+    LANGDIR="./$language"
+fi
+RET=0
 
 [ -d "$SOURCE" -o -d "$PODIR" ] || exit 1
 
-[ -d "$LANGDIR" ] && rm $LANGDIR/*.xml
+[ -d "$LANGDIR" ] && rm -r $LANGDIR
 
-echo "Creating .xml files for language $language"
+echo "Creating .xml files for language '$language':"
 for ORIGXML in `find $SOURCEDIR -name "*.xml"` ; do
-    SUBDIR=$(dirname $ORIGXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
+    BASEDIR=$(dirname $ORIGXML | sed "s:$SOURCEDIR::" | sed "s:^/::")
     BASENAME=$(basename $ORIGXML .xml)
-    PO=$PODIR/$SUBDIR/$BASENAME.$language.po
-    XML=$LANGDIR/$SUBDIR/$BASENAME.xml
+    PO=$PODIR/$BASEDIR/$BASENAME.$language.po
+    XML=$LANGDIR/$BASEDIR/$BASENAME.xml
+    DISP="$(echo $BASEDIR/$BASENAME | sed "s:^/::")"
 
-    mkdir -p $LANGDIR/$SUBDIR
+    mkdir -p $LANGDIR/$BASEDIR
 
     if [ -f $PO ] ; then
-        echo "- $SUBDIR/$BASENAME: creating translated .xml"
+        echo "- $DISP: creating translated .xml"
         po2xml $ORIGXML $PO > $XML
+        RC=$?
+        if [ $RC -ne 0 ] ; then
+            RET=$RC
+            echo "* $DISP: error $RC while executing po2xml"
+        fi
     else
-        echo "* $SUBDIR/$BASENAME: no .po file found; copying English original"
-        cp $ORIGXML $LANGDIR/$SUBDIR
+        echo "* $DISP: no .po file found; copying English original"
+        cp $ORIGXML $LANGDIR/$BASEDIR
     fi
 done
 
-exit 0
+exit $RET
diff --git a/doc/manual/scripts/update_po b/doc/manual/scripts/update_po
--- a/doc/manual/scripts/update_po
+++ b/doc/manual/scripts/update_po
@@ -14,6 +14,7 @@ fi
 language=${1:-pl}
 
 PODIR="./po"
+RET=0
 
 [ -d "$PODIR" ] || exit 1
 
@@ -27,9 +28,14 @@ for POT in `find $PODIR -name "*.pot"` ; do
     if [ -f $PO ] ; then
         echo "- $DISP"
         msgmerge -q -U --backup=simple $PO $POT
+        RC=$?
+        if [ $RC -ne 0 ] ; then
+            RET=$RC
+            echo "* $DISP: error $RC while executing msgmerge"
+        fi
     else
         echo "* No .po file found for '$DISP'."
     fi
 done
 
-exit 0
+exit $RET
diff --git a/doc/manual/scripts/update_pot b/doc/manual/scripts/update_pot
--- a/doc/manual/scripts/update_pot
+++ b/doc/manual/scripts/update_pot
@@ -13,6 +13,7 @@ fi
 WORKDIR="./integrated"
 SOURCEDIR="$WORKDIR/en"
 PODIR="./po"
+RET=0
 
 [ -d $SOURCE ] || exit 1
 
@@ -31,6 +32,11 @@ for XML in `find $SOURCEDIR -name "*.xml"` ; do
     mkdir -p $PODIR/$SUBDIR
 
     xml2pot $XML >$PODIR/$SUBDIR/$POT
+    RC=$?
+    if [ $RC -ne 0 ] ; then
+        RET=$RC
+        echo "* $XML: error $RC while executing xml2pot"
+    fi
 done
 
-exit 0
+exit $RET
