Added warning messages if needed binaries are not found
r26454

diff --git a/doc/manual/scripts/update_po b/doc/manual/scripts/update_po
--- a/doc/manual/scripts/update_po
+++ b/doc/manual/scripts/update_po
@@ -10,6 +10,10 @@ if [ "$1" = "--help" ] ; then
     echo "Usage: $0 <language>"
     exit 0
 fi
+if [ -z "`which msgmerge 2>/dev/null`" ] ; then
+    echo "ERR: Msgmerge not found, please install the gettext package"
+    exit 1
+fi
 
 language=${1:-pl}
 
diff --git a/doc/manual/scripts/update_pot b/doc/manual/scripts/update_pot
--- a/doc/manual/scripts/update_pot
+++ b/doc/manual/scripts/update_pot
@@ -10,6 +10,11 @@ if [ "$1" = "--help" ] ; then
     exit 0
 fi
 
+if [ -z "`which xml2pot 2>/dev/null`"  ] ; then
+   echo "ERR: xml2pot not found, please install the poxml package"
+   exit 1
+fi
+
 BUILDDIR="./build"
 if [ -z "$PO_USEBUILD" ] ; then
     WORKDIR="./integrated"
