When ONLINE=n, APT must not cleanup lists directory.
r30578

diff --git a/build/util/get-packages b/build/util/get-packages
--- a/build/util/get-packages
+++ b/build/util/get-packages
@@ -105,7 +105,7 @@ else
 	# offline mode.
 	APT_GET="$APT_GET --allow-unauthenticated"
 	
-	$APT_GET update || echo "Ignoring update failure in offline mode"
+	$APT_GET --no-list-cleanup update || echo "Ignoring update failure in offline mode"
 fi
 
 if [ "$PACKAGES" = update ]; then
